"use client";

import { useState } from "react";
import { Download, FileSpreadsheet, Printer, Sheet } from "lucide-react";
import * as XLSX from "xlsx";

export interface ExportRow {
  lineItem: string;
  agreed: string;
  actual: string; // human-readable string
  actualNum?: number; // numeric for Excel formatting
}

export interface SettlementExportData {
  artistName: string;
  showDate: string;
  dealType: string;
  rows: ExportRow[];      // all rows including expanded expense line items
  totalToArtist: number | null;
  settledOffPlatform: boolean;
}

interface Props {
  data: SettlementExportData;
  onPrint: () => void; // parent forces expense expansion before print
}

export function SettlementExport({ data, onPrint }: Props) {
  const [exporting, setExporting] = useState(false);

  const slug = data.artistName.toLowerCase().replace(/\s+/g, "-");
  const filename = `settlement-${slug}-${data.showDate}`;

  // ── Excel export ───────────────────────────────────────────────────────────
  function exportExcel() {
    setExporting(true);
    try {
      const header = [
        [`Settlement Worksheet — ${data.artistName}`],
        [`Show date: ${data.showDate}`],
        [`Deal type: ${data.dealType}`],
        [],
        ["LINE ITEM", "AGREED", "ACTUAL"],
      ];

      const body = data.rows.map((r) => [r.lineItem, r.agreed, r.actual]);

      const footer = [
        [],
        [
          "TOTAL TO ARTIST",
          data.settledOffPlatform ? "Entered off-platform" : "Calculated by system",
          data.totalToArtist != null
            ? `$${data.totalToArtist.toLocaleString("en-US", { minimumFractionDigits: 2 })}`
            : "—",
        ],
        [],
        ["Generated by Greenroom", "", new Date().toLocaleDateString("en-US")],
      ];

      const ws = XLSX.utils.aoa_to_sheet([...header, ...body, ...footer]);

      // Column widths
      ws["!cols"] = [{ wch: 32 }, { wch: 38 }, { wch: 18 }];

      // Bold the header rows
      const boldStyle = { font: { bold: true } };
      ["A1", "A5", "B5", "C5"].forEach((cell) => {
        if (ws[cell]) ws[cell].s = boldStyle;
      });

      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "Settlement");
      XLSX.writeFile(wb, `${filename}.xlsx`);
    } finally {
      setExporting(false);
    }
  }

  // ── PDF via print ──────────────────────────────────────────────────────────
  function exportPDF() {
    onPrint(); // parent expands expenses + triggers window.print()
  }

  return (
    <div className="settlement-export-bar px-5 py-4 border-t border-ink-100/80 flex items-center justify-between gap-4 bg-white rounded-b-lg">
      <span className="text-[11px] text-ink-400 flex items-center gap-1">
        <Download className="h-3 w-3" />
        Export worksheet
      </span>

      <div className="flex items-center gap-2">
        {/* Excel */}
        <button
          onClick={exportExcel}
          disabled={exporting}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-[11.5px] font-medium
            text-ink-700 bg-white ring-1 ring-ink-200/80 hover:bg-ink-50 hover:ring-ink-300
            transition-colors disabled:opacity-50"
        >
          <FileSpreadsheet className="h-3.5 w-3.5 text-green-600" />
          Excel (.xlsx)
        </button>

        {/* PDF */}
        <button
          onClick={exportPDF}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-[11.5px] font-medium
            text-ink-700 bg-white ring-1 ring-ink-200/80 hover:bg-ink-50 hover:ring-ink-300
            transition-colors"
        >
          <Printer className="h-3.5 w-3.5 text-rose-500" />
          PDF / Print
        </button>

        {/* Google Sheets — intent only */}
        <div className="relative group">
          <button
            disabled
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-[11.5px] font-medium
              text-ink-300 bg-white ring-1 ring-ink-100/80 cursor-not-allowed"
          >
            <Sheet className="h-3.5 w-3.5" />
            Google Sheets
          </button>
          <div className="absolute bottom-full mb-1.5 left-1/2 -translate-x-1/2 w-48 hidden group-hover:block
            bg-ink-900 text-white text-[10.5px] rounded-md px-2.5 py-1.5 text-center leading-snug pointer-events-none z-50">
            Requires Google OAuth setup — coming in a later release
          </div>
        </div>
      </div>
    </div>
  );
}
